/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FHighLow */

#ifndef _Included_FHighLow
#define _Included_FHighLow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FHighLow
 * Method:    get_samples
 * Signature: (IILjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_FHighLow_get_1samples
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     FHighLow
 * Method:    calc_fourier
 * Signature: ([III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_FHighLow_calc_1fourier
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
