/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SoundInfo */

#ifndef _Included_SoundInfo
#define _Included_SoundInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef SoundInfo_window_size
#define SoundInfo_window_size 256L
/*
 * Class:     SoundInfo
 * Method:    get_samples
 * Signature: (IILjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_SoundInfo_get_1samples
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     SoundInfo
 * Method:    calc_fourier
 * Signature: ([III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_SoundInfo_calc_1fourier
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
